site_name: lzx's wiki
nav:
  - 主页: index.md
  - 比赛总结:
    - 前言: match/index.md
    - CSP2022: match/csp2022.md
theme:
  name: 'material'
  language: en
  logo: assets/logo.png
  palette:
    primary: green
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
plugins:
  - search:
      lang: 
        - en
        - zh
copyright: Copyright &copy; 2022 lzx19
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
      permalink: true
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js