site_name: lzx's wiki
nav:
    - 主页: index.md
    - 学习笔记: study-note.md
    - 比赛总结: match-note.md
theme:
  name: 'material'
  language: zh
  logo: assets/logo.png
  palette:
    primary: green
    accent: light blue
  features:
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
plugins:
  - search:
      lang: 
        - en
        - zh
copyright: Copyright &copy; 2022 lzx19